<?php

if (function_exists('acf_add_local_field_group')) :

    acf_add_local_field_group(array(
        'key' => 'group_5e7a03e037a03',
        'title' => 'Event',
        'fields' => array(
            array(
                'key' => 'field_5e7a03e245677',
                'label' => 'Event name',
                'name' => 'event_name',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'Name of the Event',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5e7a040745678',
                'label' => 'Event Featured Image',
                'name' => 'event_image',
                'type' => 'image',
                'instructions' => 'Please input a featured image',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '.png,.jpg,.jpeg',
            ),
            array(
                'key' => 'field_5e7a04d545679',
                'label' => 'Event Description',
                'name' => 'event_desc',
                'type' => 'textarea',
                'instructions' => 'Here you enter an description for this event',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_5e7a116a3774a',
                'label' => 'Arranger',
                'name' => 'arranger',
                'type' => 'text',
                'instructions' => 'Please enter who it is that arranges the Event',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Gathenhielmska Huset',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5e7a05294567a',
                'label' => 'Additional Information',
                'name' => 'extra_info',
                'type' => 'text',
                'instructions' => 'If there are any additional information that the participants need to know you can enter it here',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'Additional information...',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5e7a05e24567b',
                'label' => 'Event Start',
                'name' => 'event_start',
                'type' => 'date_time_picker',
                'instructions' => 'Please enter when the Event starts',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'F j, Y H:i',
                'return_format' => 'F j, Y H:i',
                'first_day' => 1,
            ),
            array(
                'key' => 'field_5e7a06544567c',
                'label' => 'Event End',
                'name' => 'event_end',
                'type' => 'date_time_picker',
                'instructions' => 'Please enter when the Event ends',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'F j, Y H:i',
                'return_format' => 'F j, Y H:i',
                'first_day' => 1,
            ),
            array(
                'key' => 'field_5e7a06744567d',
                'label' => 'Link to Ticket site',
                'name' => 'ticket_url',
                'type' => 'url',
                'instructions' => 'If you are selling tickets, please enter a link to your preferred ticket site',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://www.ticket_site.se',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'event',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'permalink',
            1 => 'the_content',
            2 => 'excerpt',
            3 => 'discussion',
            4 => 'comments',
            5 => 'revisions',
            6 => 'slug',
            8 => 'format',
            9 => 'page_attributes',
            10 => 'featured_image',
            11 => 'categories',
            12 => 'tags',
            13 => 'send-trackbacks',
        ),
        'active' => true,
        'description' => '',
    ));

endif;
